# Generated by Django 2.2.5 on 2020-02-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField(auto_now=True)),
                ('end_time', models.DateField()),
                ('owner', models.EmailField(max_length=254)),
                ('rental_unique_id', models.TextField()),
                ('total_cost', models.FloatField()),
                ('charge_id', models.TextField()),
                ('refund_status', models.BooleanField()),
                ('server_id', models.TextField()),
            ],
        ),
    ]
