# Generated by Django 2.2.5 on 2020-03-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='expired',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
