# Generated by Django 2.2.5 on 2020-03-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='rental',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_owner',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
