# Generated by Django 2.2.5 on 2020-03-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_auto_20200315_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_product_names',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
