# Generated by Django 2.2.5 on 2020-02-28 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment_details',
        ),
    ]
