# Generated by Django 2.2.5 on 2020-02-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0002_delete_payment_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_owner', models.EmailField(max_length=254)),
                ('card_number', models.TextField()),
                ('card_csv', models.TextField()),
            ],
        ),
    ]
