# Generated by Django 2.2.5 on 2020-02-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_details',
            name='exp_month',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment_details',
            name='exp_year',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
