# Generated by Django 2.2.5 on 2020-02-26 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='server_component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.TextField(max_length=20)),
                ('part_type', models.TextField()),
                ('rental_cost', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('hardware_cost', models.FloatField()),
                ('specifications', models.TextField()),
                ('socket_type', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='unrented_server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary_id', models.TextField()),
                ('server_id', models.TextField()),
                ('creator', models.EmailField(default=None, max_length=254)),
                ('prebuilt', models.BooleanField(default=True)),
                ('CPU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CPU', to='servers.server_component')),
                ('GPU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GPU', to='servers.server_component')),
                ('HDD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HDD', to='servers.server_component')),
                ('RAM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RAM', to='servers.server_component')),
                ('SSD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SSD', to='servers.server_component')),
                ('motherboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motherboard', to='servers.server_component')),
            ],
        ),
        migrations.CreateModel(
            name='rented_server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary_id', models.TextField()),
                ('server_id', models.TextField()),
                ('server_owner', models.EmailField(max_length=254)),
                ('CPU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CPU_rented', to='servers.server_component')),
                ('GPU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GPU_rented', to='servers.server_component')),
                ('HDD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HDD_rented', to='servers.server_component')),
                ('RAM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RAM_rented', to='servers.server_component')),
                ('SSD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SSD_rented', to='servers.server_component')),
                ('motherboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motherboard_rented', to='servers.server_component')),
            ],
        ),
    ]
