# Generated by Django 2.2.5 on 2020-02-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rented_server',
            name='secondary_id',
            field=models.TextField(default='<built-in function id>'),
        ),
        migrations.AlterField(
            model_name='unrented_server',
            name='secondary_id',
            field=models.TextField(default='<built-in function id>'),
        ),
    ]
