# Generated by Django 2.2.5 on 2020-03-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_auto_20200226_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='unrented_server',
            name='user_made',
            field=models.BooleanField(default=False),
        ),
    ]
