# Generated by Django 2.2.5 on 2020-03-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_unrented_server_user_made'),
    ]

    operations = [
        migrations.AddField(
            model_name='unrented_server',
            name='shared_publically',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unrented_server',
            name='user_saved',
            field=models.BooleanField(default=False),
        ),
    ]
