# Generated by Django 2.2.5 on 2020-04-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0006_auto_20200423_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server_component',
            name='hardware_cost',
            field=models.FloatField(),
        ),
    ]
