# Generated by Django 2.2.5 on 2020-04-25 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0007_auto_20200423_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server_component',
            name='quantity',
        ),
    ]
